@baseUrl =http://localhost:3000/webApp/my_tournament

@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWZyZXNoVG9rZW5JZCI6MjI4MDU5LCJvd25lcklkIjo4LCJ1c2VySWQiOjMsImlhdCI6MTY2MzQyODEzMSwiZXhwIjoxNjYzNTE0NTMxLCJpc3MiOiJQcmltZXhvcC5jb20ifQ.jAmFX514ma1JGonkZC0NRl9AZjedrth0odnH-PWMvS0

@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcklkIjo4LCJ1c2VySWQiOjMsImlhdCI6MTY2MzQyODEzMSwiZXhwIjoxNjYzNDI4NzMxLCJpc3MiOiJQcmltZXhvcC5jb20ifQ.tl2TuN-3NfkTKVerVcnATL3eE1-Ptu6WbwVcjvEK-kE



### get basic details about app
GET {{baseUrl}}
content-type: application/json

### get basic details about app
GET {{baseUrl}}/app/getDetails
content-type: application/json


### Register 
POST {{baseUrl}}/auth/register
content-type: application/json

{
    "fullName":"Adarsh user",
    "email":"Rajeadarsh15@gmail.com",
    "mobileNumber":"7775814761",
    "password":"7875753356" 
}

### login 
POST {{baseUrl}}/auth/login
content-type: application/json

{
    
    "email":"Rajeadarsh15@gmail.com",
   
    "password":"7875753356" 
}

### refreshToken 
GET {{baseUrl}}/auth/refreshToken
content-type: application/json
Authorization: Bearer {{refreshToken}}

### get basic details about user
GET {{baseUrl}}/basic/
content-type: application/json
Authorization: Bearer {{accessToken}}

### initiating transaction
POST {{baseUrl}}/paytm/init
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "txnAmount":1,
    "clientLocationUrl":"primexop.com"
}


### get basic details about app
GET {{baseUrl}}/wallet/walletHistory/0/10
content-type: application/json
Authorization: Bearer {{accessToken}}

### get basic details about user
GET {{baseUrl}}/basic/getWebApkInitData
content-type: application/json
Authorization: Bearer {{accessToken}}
